version: '3.8'

services:
  litellm-proxy:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LITELLM_PROXY_HOST=0.0.0.0
      - LITELLM_PROXY_PORT=8000
    env_file:
      - .secret-env.env
    volumes:
      - ./.secret-config.json:/app/.secret-config.json
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
